import pg from 'pg';
const url = process.env.DATABASE_URL;
const c = new pg.Client({ connectionString: url, ssl: url.includes('localhost')?false:{rejectUnauthorized:false} });
await c.connect();
const out = {};
const grab = async (key, sql) => { try { out[key] = (await c.query(sql)).rows; } catch(e){ out[key] = 'ERR '+e.message; } };
await grab('transactions', `select id, merchant_id, status from transactions order by merchant_id, id`);
await grab('stock', `select id, merchant_id from stock_items order by merchant_id limit 20`);
await grab('tenants', `select id, merchant_id from tenant_profiles order by merchant_id limit 20`);
await grab('invoices', `select id, merchant_id from invoices_rent_requests order by merchant_id limit 20`);
await grab('clients', `select id, merchant_id from client_profiles order by merchant_id limit 20`);
await grab('quotes', `select id, merchant_id from quotes order by merchant_id limit 20`);
await grab('jobinv', `select id, merchant_id from job_invoices order by merchant_id limit 20`);
await grab('stones', `select id, merchant_id from tapt_stones order by merchant_id limit 20`);
await grab('refunds', `select id, merchant_id from refunds order by merchant_id limit 20`);
await grab('users', `select id, merchant_id, role from users order by merchant_id`);
await grab('schedules', `select id, merchant_id from active_schedules limit 20`);
console.log(JSON.stringify(out, null, 1));
await c.end();
