import { randomBytes, randomUUID } from "node:crypto";
import { LANDING_DEMO_ACTIONS, LANDING_DEMO_TTL_MS, isLandingDemoAction, type LandingDemoActionRequest, type LandingDemoState } from "@shared/landing-demo";
export type LandingDemoSession = { token: string; state: LandingDemoState; expiresAtMs: number };
const sessions = new Map<string, LandingDemoSession>(); const scenes = new Set(["retail-sale", "retail-tip", "property-rent", "trades-quote"]);
function purge(now = Date.now()) { for (const [id, s] of sessions) if (s.expiresAtMs <= now) sessions.delete(id); while (sessions.size > 256) sessions.delete(sessions.keys().next().value!); }
export function createLandingDemoSession(now = Date.now()) { purge(now); const expiresAtMs = now + LANDING_DEMO_TTL_MS; const token = randomBytes(32).toString("base64url"); const state: LandingDemoState = { sessionId: randomUUID(), expiresAt: new Date(expiresAtMs).toISOString(), scene: "retail-sale", step: 0, mode: "cinematic", lastAction: null, transaction: { status: "idle", amount: 24.5, label: "Flat white + toast" } }; sessions.set(token, { token, state, expiresAtMs }); return { token, state }; }
export function getLandingDemoSession(token: string | undefined, now = Date.now()): LandingDemoSession | null { if (!token) return null; const s = sessions.get(token); if (!s || s.expiresAtMs <= now) { if (s) sessions.delete(token); return null; } return s; }
export function applyLandingDemoAction(session: LandingDemoSession, input: unknown): LandingDemoState | null { if (!input || typeof input !== "object") return null; const r = input as Partial<LandingDemoActionRequest>; if (!isLandingDemoAction(r.action)) return null; if (r.action === "selectScene") { if (typeof r.scene !== "string" || !scenes.has(r.scene)) return null; session.state.scene = r.scene; session.state.step = 0; } else if (r.action === "tap") { if (typeof r.target !== "string" || r.target.length > 64) return null; session.state.step = Math.min(99, session.state.step + 1); if (r.target === "pay" || r.target === "confirm") session.state.transaction.status = "paid"; } else if (r.action === "reset") { session.state.step = 0; session.state.transaction.status = "idle"; } else if (r.action === "setMode") { if (r.mode !== "cinematic" && r.mode !== "live") return null; session.state.mode = r.mode; } session.state.lastAction = r.action; return session.state; }
export const landingDemoAllowedActions = () => LANDING_DEMO_ACTIONS;
