import jsPDF from 'jspdf';
import type { Transaction, Merchant } from '@shared/schema';

export interface ReportData {
  totalTransactions: number;
  completedTransactions: number;
  totalRevenue: number;
  currentProviderCost: number;
  ourCost: number;
  savings: number;
  currentProviderRate: number;
  ourRate: number;
  dateRange: { start: Date | null; end: Date | null };
  averageTransactionValue: number;
  transactionsByStatus: { [key: string]: number };
}

export async function generateBusinessReportPdf(
  analytics: ReportData,
  transactions: Transaction[],
  merchant: Merchant
): Promise<Buffer> {
  const pdf = new jsPDF();
  
  // Set up fonts and colors
  pdf.setFont('helvetica');
  
  // Header
  pdf.setFontSize(20);
  pdf.setTextColor(0, 100, 0); // Green color
  pdf.text('Tapt Business Report', 20, 30);
  
  // Merchant info
  pdf.setFontSize(12);
  pdf.setTextColor(0, 0, 0);
  pdf.text(`Business: ${merchant.businessName || merchant.name}`, 20, 45);
  
  // Date range
  const dateRangeText = analytics.dateRange.start || analytics.dateRange.end
    ? `Period: ${analytics.dateRange.start?.toLocaleDateString('en-NZ') || 'Beginning'} - ${analytics.dateRange.end?.toLocaleDateString('en-NZ') || 'Today'}`
    : 'Period: All Time';
  pdf.text(dateRangeText, 20, 55);
  pdf.text(`Generated: ${new Date().toLocaleDateString('en-NZ')}`, 20, 65);
  
  // Summary section
  pdf.setFontSize(16);
  pdf.setTextColor(0, 100, 0);
  pdf.text('Executive Summary', 20, 85);
  
  pdf.setFontSize(11);
  pdf.setTextColor(0, 0, 0);
  let yPos = 100;
  
  // Key metrics
  const metrics = [
    `Total Transactions: ${analytics.totalTransactions}`,
    `Completed Transactions: ${analytics.completedTransactions}`,
    `Total Revenue: $${analytics.totalRevenue.toFixed(2)} NZD`,
    `Average Transaction: $${analytics.averageTransactionValue.toFixed(2)} NZD`,
    ``,
    `Cost Comparison:`,
    `  Current Provider (${analytics.currentProviderRate.toFixed(2)}%): $${analytics.currentProviderCost.toFixed(2)}`,
    `  Tapt (0.20 flat fee): $${analytics.ourCost.toFixed(2)}`,
    `  Total Savings: $${analytics.savings.toFixed(2)} NZD`,
  ];
  
  metrics.forEach(metric => {
    if (metric === '') {
      yPos += 5;
    } else {
      pdf.text(metric, 20, yPos);
      yPos += 12;
    }
  });
  
  // Transaction breakdown by status
  yPos += 10;
  pdf.setFontSize(16);
  pdf.setTextColor(0, 100, 0);
  pdf.text('Transaction Breakdown', 20, yPos);
  yPos += 20;
  
  pdf.setFontSize(11);
  pdf.setTextColor(0, 0, 0);
  
  Object.entries(analytics.transactionsByStatus).forEach(([status, count]) => {
    pdf.text(`${status.charAt(0).toUpperCase() + status.slice(1)}: ${count}`, 20, yPos);
    yPos += 12;
  });
  
  // Recent transactions table (last 10)
  if (transactions.length > 0) {
    yPos += 20;
    pdf.setFontSize(16);
    pdf.setTextColor(0, 100, 0);
    pdf.text('Recent Transactions', 20, yPos);
    yPos += 20;
    
    // Table headers
    pdf.setFontSize(9);
    pdf.setTextColor(0, 0, 0);
    pdf.text('Date', 20, yPos);
    pdf.text('Item', 50, yPos);
    pdf.text('Amount', 120, yPos);
    pdf.text('Status', 160, yPos);
    yPos += 8;
    
    // Draw header line
    pdf.line(20, yPos, 190, yPos);
    yPos += 8;
    
    // Show last 10 transactions
    const recentTransactions = transactions
      .sort((a, b) => new Date(b.createdAt || 0).getTime() - new Date(a.createdAt || 0).getTime())
      .slice(0, 10);
    
    recentTransactions.forEach(transaction => {
      if (yPos > 270) { // Page break
        pdf.addPage();
        yPos = 30;
      }
      
      const date = transaction.createdAt 
        ? new Date(transaction.createdAt).toLocaleDateString('en-NZ')
        : 'N/A';
      
      pdf.text(date, 20, yPos);
      pdf.text(transaction.itemName.substring(0, 20), 50, yPos);
      pdf.text(`$${parseFloat(transaction.price).toFixed(2)}`, 120, yPos);
      pdf.text(transaction.status, 160, yPos);
      yPos += 10;
    });
  }
  
  // Footer
  pdf.setFontSize(8);
  pdf.setTextColor(128, 128, 128);
  pdf.text('Generated by Tapt Payment Terminal', 20, 280);
  pdf.text('https://tapt.co.nz', 140, 280);
  
  return Buffer.from(pdf.output('arraybuffer'));
}