/* Reusable @react-pdf building blocks shared by all eleven reports. Report
   files never touch raw @react-pdf styling — they compose <ReportPage>,
   <KpiRow>, <DataTable>, <ReportBarChart>, etc. */
import React from "react";
import { Document, Page, View, Text, Svg, Rect, Path, Circle, G } from "@react-pdf/renderer";

import { COLORS, PAGE, styles, ensureFonts } from "./theme";
import { fmtNZD } from "../report-utils";

/* Content width of an A4 page inside the horizontal padding, in points.
   595.28pt (A4 width) − 2×40pt padding ≈ 515pt. Charts and equal-flex label
   rows both assume this width so bars and their labels line up. */
export const CONTENT_W = 515;

export interface MerchantHeader {
  businessName?: string | null;
  gstNumber?: string | null;
  nzbn?: string | null;
  gstRegistered?: boolean | null;
}

/* ── Page shell: cover band on p1, running header p2+, footer everywhere ── */
export function ReportPage({
  merchant,
  title,
  period,
  children,
}: {
  merchant: MerchantHeader;
  title: string;
  period?: string;
  children: React.ReactNode;
}) {
  ensureFonts();
  const meta = [
    merchant.gstNumber ? `GST ${merchant.gstNumber}` : null,
    merchant.nzbn ? `NZBN ${merchant.nzbn}` : null,
  ]
    .filter(Boolean)
    .join("   ·   ");

  return (
    <Page size={PAGE.size} style={styles.page} wrap>
      {/* Running header — only pages 2+ (cover carries the branding on p1) */}
      <View
        style={styles.runHeader}
        fixed
        render={({ pageNumber }) =>
          pageNumber > 1 ? (
            <>
              <Text>{merchant.businessName || "TaptPay"}</Text>
              <Text>{title}</Text>
            </>
          ) : null
        }
      />

      {/* Cover band (page 1 only) */}
      <View style={styles.cover}>
        <Text style={styles.coverBiz}>{merchant.businessName || "TaptPay Merchant"}</Text>
        {!!meta && <Text style={styles.coverMeta}>{meta}</Text>}
        <Text style={styles.coverTitle}>{title}</Text>
        {!!period && <Text style={styles.coverPeriod}>{period}</Text>}
      </View>

      {children}

      {/* Footer with page numbers */}
      <View
        style={styles.footer}
        fixed
        render={({ pageNumber, totalPages }) => (
          <>
            <Text>Generated by TaptPay · {new Date().toLocaleDateString("en-NZ", { timeZone: "Pacific/Auckland" })}</Text>
            <Text>
              Page {pageNumber} of {totalPages}
            </Text>
          </>
        )}
      />
    </Page>
  );
}

export function Document1({ children }: { children: React.ReactNode }) {
  return <Document>{children}</Document>;
}

export function SectionTitle({ children }: { children: React.ReactNode }) {
  return <Text style={styles.sectionTitle}>{children}</Text>;
}

/* ── KPI cards ──────────────────────────────────────────────────────── */
export interface Kpi {
  label: string;
  value: string;
  sub?: string;
}
export function KpiRow({ items }: { items: Kpi[] }) {
  return (
    <View style={styles.kpiRow}>
      {items.map((k, i) => (
        <View key={i} style={styles.kpiCard}>
          <Text style={styles.kpiLabel}>{k.label}</Text>
          <Text style={styles.kpiValue}>{k.value}</Text>
          {!!k.sub && <Text style={styles.kpiSub}>{k.sub}</Text>}
        </View>
      ))}
    </View>
  );
}

/* ── Table ──────────────────────────────────────────────────────────── */
export interface Column<T> {
  header: string;
  /** flex weight for the column's width */
  flex: number;
  align?: "left" | "right" | "center";
  render: (row: T, index: number) => React.ReactNode;
}
export function DataTable<T>({
  columns,
  rows,
  foot,
  emptyText = "No records in this period.",
}: {
  columns: Column<T>[];
  rows: T[];
  foot?: React.ReactNode[]; // one node per column
  emptyText?: string;
}) {
  const alignStyle = (a?: string) => (a === "right" ? styles.right : a === "center" ? styles.center : undefined);

  return (
    <View>
      {/* Header repeats on every page via fixed */}
      <View style={styles.tHeadRow} fixed>
        {columns.map((c, i) => (
          <Text key={i} style={[styles.tHeadCell, { flex: c.flex }, alignStyle(c.align)]}>
            {c.header}
          </Text>
        ))}
      </View>

      {rows.length === 0 ? (
        <Text style={styles.empty}>{emptyText}</Text>
      ) : (
        rows.map((row, r) => (
          <View key={r} style={[styles.tRow, r % 2 === 1 ? styles.tRowAlt : {}]} wrap={false}>
            {columns.map((c, i) => (
              <View key={i} style={[styles.tCell, { flex: c.flex }, alignStyle(c.align)]}>
                {typeof c.render(row, r) === "string" || typeof c.render(row, r) === "number" ? (
                  <Text style={alignStyle(c.align)}>{c.render(row, r)}</Text>
                ) : (
                  c.render(row, r)
                )}
              </View>
            ))}
          </View>
        ))
      )}

      {foot && rows.length > 0 && (
        <View style={styles.tFootRow} wrap={false}>
          {columns.map((c, i) => (
            <Text key={i} style={[styles.tFootCell, { flex: c.flex }, alignStyle(c.align)]}>
              {foot[i] ?? ""}
            </Text>
          ))}
        </View>
      )}
    </View>
  );
}

/* Money/text/status cell helpers so report files stay declarative. */
export function Money({ cents, bold }: { cents: number; bold?: boolean }) {
  return <Text style={[styles.right, bold ? { fontWeight: 700 } : {}]}>{fmtNZD(cents)}</Text>;
}
export function StatusText({ kind, label }: { kind: "paid" | "overdue" | "sent" | "muted"; label: string }) {
  const s =
    kind === "paid" ? styles.statusPaid : kind === "overdue" ? styles.statusOverdue : kind === "sent" ? styles.statusSent : styles.statusMuted;
  return <Text style={s}>{label}</Text>;
}

/* ── Bar chart (vector port of the dashboard's RentBarChart) ─────────── */
export interface Bar {
  label: string;
  valueCents: number;
}
/** Solid navy bars (collected) with optional dashed sky "ghost" outlines
   (billed but uncollected) — the exact visual language of the app chart. */
export function ReportBarChart({
  bars,
  ghost = [],
  width = CONTENT_W,
  height = 132,
}: {
  bars: Bar[];
  ghost?: Bar[];
  width?: number;
  height?: number;
}) {
  const n = bars.length;
  if (!n) return null;
  const chartH = height - 22; // leave room for value labels above bars
  const maxV = Math.max(1, ...bars.map((b) => b.valueCents), ...ghost.map((b) => b.valueCents));
  const colW = width / n;
  const barW = Math.min(colW * 0.5, 30);
  const scale = (v: number) => (v / maxV) * (chartH - 14);

  return (
    <View>
      <Svg width={width} height={height}>
        {/* baseline */}
        <Path d={`M0 ${chartH} L${width} ${chartH}`} stroke={COLORS.hairline} strokeWidth={1} />
        {bars.map((b, i) => {
          const cx = i * colW + colW / 2;
          const g = ghost[i]?.valueCents ?? 0;
          const gh = scale(g);
          const bh = scale(b.valueCents);
          return (
            <G key={i}>
              {g > 0 && (
                <Rect
                  x={cx - barW / 2}
                  y={chartH - gh}
                  width={barW}
                  height={gh}
                  rx={3}
                  fill="none"
                  stroke={COLORS.sky}
                  strokeWidth={1.2}
                  strokeDasharray="3 3"
                />
              )}
              <Rect x={cx - barW / 2} y={chartH - bh} width={barW} height={Math.max(bh, 1.5)} rx={3} fill={COLORS.navy} />
            </G>
          );
        })}
      </Svg>
      {/* value labels */}
      <View style={{ flexDirection: "row", marginTop: -Math.round(height) }}>
        {bars.map((b, i) => (
          <Text key={i} style={{ flex: 1, textAlign: "center", fontSize: 7.5, fontWeight: 600, color: COLORS.sky }}>
            {b.valueCents > 0 ? fmtNZD(b.valueCents) : ""}
          </Text>
        ))}
      </View>
      {/* x-axis labels */}
      <View style={{ flexDirection: "row", marginTop: 4 }}>
        {bars.map((b, i) => (
          <Text key={i} style={{ flex: 1, textAlign: "center", fontSize: 7, fontWeight: 600, color: COLORS.muted }}>
            {b.label}
          </Text>
        ))}
      </View>
    </View>
  );
}

/* ── Donut (quote conversion, split share, etc.) ────────────────────── */
export function DonutStat({
  pct,
  centerLabel,
  caption,
  size = 108,
}: {
  pct: number; // 0..100
  centerLabel: string;
  caption?: string;
  size?: number;
}) {
  const r = size / 2 - 8;
  const c = 2 * Math.PI * r;
  const filled = Math.max(0, Math.min(100, pct)) / 100;
  const cx = size / 2;
  return (
    <View style={{ flexDirection: "row", alignItems: "center", gap: 14 }}>
      <Svg width={size} height={size}>
        <G>
          <Circle cx={cx} cy={cx} r={r} stroke={COLORS.skyWash} strokeWidth={10} fill="none" />
          <Circle
            cx={cx}
            cy={cx}
            r={r}
            stroke={COLORS.sky}
            strokeWidth={10}
            fill="none"
            strokeDasharray={`${(c * filled).toFixed(1)} ${c.toFixed(1)}`}
            strokeLinecap="round"
            transform={`rotate(-90 ${cx} ${cx})`}
          />
        </G>
      </Svg>
      <View>
        <Text style={{ fontSize: 22, fontWeight: 700, color: COLORS.navy, letterSpacing: -0.5 }}>{centerLabel}</Text>
        {!!caption && <Text style={{ fontSize: 8.5, color: COLORS.muted, fontWeight: 500, marginTop: 2 }}>{caption}</Text>}
      </View>
    </View>
  );
}
